//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGKDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGKLocation
    {
        public int IDLocatie { get; set; }
        public string NumeLocatie { get; set; }
        public string IPs { get; set; }
        public string Port { get; set; }
        public string GlAuth { get; set; }
        public string GlCheckSite { get; set; }
        public string GlMenuSite { get; set; }
        public string GlIDStatie { get; set; }
        public string GlIDAngajat { get; set; }
        public string GlIDClient { get; set; }
        public string GlStoreID { get; set; }
        public string GlPartnerName { get; set; }
        public string GlStoreEnvironment { get; set; }
        public string Gl2IDStatie { get; set; }
        public string Gl2IDAngajat { get; set; }
        public string Gl2IDClient { get; set; }
        public string Gl2StoreID { get; set; }
        public string Gl2PartnerName { get; set; }
        public string Gl2StoreEnvironment { get; set; }
        public string SiteIDStatie { get; set; }
        public string SiteIDAngajat { get; set; }
        public string SiteIDClient { get; set; }
        public Nullable<bool> GlAdaugaPlata { get; set; }
        public Nullable<bool> Gl2AdaugaPlata { get; set; }
        public string SiteIPLocal { get; set; }
    }
}
