//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessDeniedLog
    {
        public System.DateTime AccessDeniedDateTime { get; set; }
        public int StationID { get; set; }
        public string AccessDeniedType { get; set; }
        public Nullable<int> AttemptedAccessCode { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string AttemptedFeatureName { get; set; }
        public int AutoID { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
    
        public virtual EmployeeFile EmployeeFile { get; set; }
        public virtual StationSetting StationSetting { get; set; }
    }
}
