//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvizeDetail
    {
        public int AutoID { get; set; }
        public Nullable<int> AvizID { get; set; }
        public Nullable<int> InventoryItemID { get; set; }
        public string InventoryItemText { get; set; }
        public string UM { get; set; }
        public Nullable<float> Cantitate { get; set; }
        public Nullable<float> PretUnitar { get; set; }
        public Nullable<float> Valoare { get; set; }
        public Nullable<int> IGID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Avize Avize { get; set; }
    }
}
