//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvizeInterne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvizeInterne()
        {
            this.AvizeInterneDetails = new HashSet<AvizeInterneDetail>();
        }
    
        public int AvizID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Numar { get; set; }
        public Nullable<int> GestiuneSursa { get; set; }
        public Nullable<int> GestiuneDestinatie { get; set; }
        public string DlgNume { get; set; }
        public string DlgBI { get; set; }
        public string DlgEliberat { get; set; }
        public string DlgMijTrans { get; set; }
        public string DlgNrAuto { get; set; }
        public string Observatii { get; set; }
        public string Serie { get; set; }
        public Nullable<int> NrNIR { get; set; }
        public string SerieNIR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvizeInterneDetail> AvizeInterneDetails { get; set; }
    }
}
