//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCTicket
    {
        public int TicketID { get; set; }
        public Nullable<System.DateTime> TicketDateTime { get; set; }
        public Nullable<bool> Processed { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
