//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BileteInHouse
    {
        public int BiletID { get; set; }
        public Nullable<System.DateTime> BiletDateTime { get; set; }
        public Nullable<int> Serie { get; set; }
        public Nullable<float> ValoareIntrare { get; set; }
        public Nullable<float> ValoareConsum { get; set; }
        public Nullable<float> RealIntrare { get; set; }
        public Nullable<float> RealConsum { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
