//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFlowScadente
    {
        public int ScadentaID { get; set; }
        public Nullable<int> Tip { get; set; }
        public Nullable<int> SursaID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Descriere { get; set; }
        public string TipDocument { get; set; }
        public string NumarDocument { get; set; }
        public Nullable<float> Suma { get; set; }
        public Nullable<int> ContID { get; set; }
        public Nullable<int> CategorieID { get; set; }
        public Nullable<bool> Achitata { get; set; }
        public Nullable<int> OperatiuneID { get; set; }
        public Nullable<int> FurnizorID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
