//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFlowEstimareObiectiveDetail
    {
        public Nullable<int> ObiectivID { get; set; }
        public int ObiectivDetailsID { get; set; }
        public Nullable<float> Anual { get; set; }
        public Nullable<float> Mediu { get; set; }
        public Nullable<float> L1 { get; set; }
        public Nullable<float> L2 { get; set; }
        public Nullable<float> L3 { get; set; }
        public Nullable<float> L4 { get; set; }
        public Nullable<float> L5 { get; set; }
        public Nullable<float> L6 { get; set; }
        public Nullable<float> L7 { get; set; }
        public Nullable<float> L8 { get; set; }
        public Nullable<float> L9 { get; set; }
        public Nullable<float> L10 { get; set; }
        public Nullable<float> L11 { get; set; }
        public Nullable<float> L12 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
