//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFlowObiectiveBugetDetail
    {
        public int DetailID { get; set; }
        public Nullable<int> ObiectivID { get; set; }
        public Nullable<int> CategorieID { get; set; }
    }
}
