//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFlowPreluareVanzari
    {
        public string SursaID { get; set; }
        public string DescriereSursa { get; set; }
        public Nullable<int> TipOperatiune { get; set; }
        public Nullable<int> Cont1ID { get; set; }
        public Nullable<int> Cont2ID { get; set; }
        public Nullable<int> CategorieID { get; set; }
    }
}
