//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComenziProductieDetaliiEM
    {
        public int AutoID { get; set; }
        public Nullable<int> IDComanda { get; set; }
        public Nullable<int> IDMenuItem { get; set; }
        public Nullable<int> IDGestiune { get; set; }
        public Nullable<float> Cantitate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual ComenziProductieEM ComenziProductieEM { get; set; }
    }
}
