//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComenziProductieEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComenziProductieEM()
        {
            this.ComenziProductieDetaliiEMs = new HashSet<ComenziProductieDetaliiEM>();
        }
    
        public int IDComanda { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string IDComenziProductie { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDActAtasat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComenziProductieDetaliiEM> ComenziProductieDetaliiEMs { get; set; }
    }
}
