//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorespondenteAprovizionari
    {
        public int AutoID { get; set; }
        public Nullable<int> IDGestiune { get; set; }
        public string NumeGestiune { get; set; }
        public Nullable<int> IdGrup { get; set; }
        public string NumeGrup { get; set; }
        public string Debit { get; set; }
        public string Credit { get; set; }
        public string IDGestiuneDeAfisat { get; set; }
    }
}
