//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRTicket
    {
        public int CRTicketID { get; set; }
        public Nullable<int> CRID { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> TotalI { get; set; }
        public Nullable<double> TotalN { get; set; }
        public string TicketStatus { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
