//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRTicketDetail
    {
        public int CRTicketDetailsID { get; set; }
        public Nullable<int> CRTicketID { get; set; }
        public Nullable<int> OrderTransactionID { get; set; }
        public string TicketDetailsStatus { get; set; }
    }
}
