//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerFile()
        {
            this.BadCheckFiles = new HashSet<BadCheckFile>();
            this.CustomerCredits = new HashSet<CustomerCredit>();
            this.FreqDinerTrackings = new HashSet<FreqDinerTracking>();
            this.OnAccountCharges = new HashSet<OnAccountCharge>();
            this.OrderHeaders = new HashSet<OrderHeader>();
            this.PrankCallFiles = new HashSet<PrankCallFile>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNotes { get; set; }
        public string DeliveryAddress { get; set; }
        public string CrossStreet { get; set; }
        public string ZipCode { get; set; }
        public string DeliveryRemarks { get; set; }
        public Nullable<float> DeliveryCharge { get; set; }
        public Nullable<float> DeliveryComp { get; set; }
        public string ScanCode { get; set; }
        public string AccountCode { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string CompanyName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<short> VIPType { get; set; }
        public string PictureName { get; set; }
        public Nullable<short> AnniversaryMonth { get; set; }
        public Nullable<short> BirthMonth { get; set; }
        public Nullable<System.DateTime> CustomerSinceDate { get; set; }
        public Nullable<float> TotalSpent { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<float> AverageOrder { get; set; }
        public Nullable<System.DateTime> LastOrderDate { get; set; }
        public Nullable<float> LastOrderAmount { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadCheckFile> BadCheckFiles { get; set; }
        public virtual CustomerCreditAccount CustomerCreditAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCredit> CustomerCredits { get; set; }
        public virtual ZipCode ZipCode1 { get; set; }
        public virtual FreqDinerFile FreqDinerFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreqDinerTracking> FreqDinerTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnAccountCharge> OnAccountCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHeader> OrderHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrankCallFile> PrankCallFiles { get; set; }
    }
}
