//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEvent
    {
        public int EventID { get; set; }
        public string Denumire { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> NrParticipanti { get; set; }
        public Nullable<int> Durata { get; set; }
        public string DateContact { get; set; }
        public Nullable<int> CostID { get; set; }
        public string AlteDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<float> TotalHours { get; set; }
        public Nullable<float> TotalHoursCost { get; set; }
        public Nullable<float> TotalOrdersCost { get; set; }
        public Nullable<float> TotalCost { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
