//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomPrinterType
    {
        public int PrinterTypeID { get; set; }
        public string PrinterTypeName { get; set; }
        public string FontBold { get; set; }
        public string FontNoBold { get; set; }
        public string FontLarge { get; set; }
        public string FontSmall { get; set; }
        public string FontRed { get; set; }
        public string FontNoRed { get; set; }
        public string CashDrawerBel { get; set; }
        public string LineFeed { get; set; }
        public string AutoCut { get; set; }
        public string Buzzard { get; set; }
        public string LargeFontColumns { get; set; }
        public string SmallFontColumns { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string Drawer2Bel { get; set; }
        public string BeginBarcode { get; set; }
        public string EndBarcode { get; set; }
        public Nullable<bool> ManualAutoCut { get; set; }
        public string InitializeCode { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
