//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCreditAccount
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MailingAddress { get; set; }
        public string MailingZipCode { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string DriverLicenseNumber { get; set; }
        public Nullable<System.DateTime> DriverLicenseExpireDate { get; set; }
        public float TotalCreditLimit { get; set; }
        public Nullable<System.DateTime> CreditAccountExpireDate { get; set; }
        public string ScanCode { get; set; }
        public string CreditAccountStatus { get; set; }
        public string CreditAccountNotes { get; set; }
        public int AutoID { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual ZipCode ZipCode { get; set; }
        public virtual CustomerFile CustomerFile { get; set; }
    }
}
