//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerHourCost
    {
        public int CostID { get; set; }
        public string Name { get; set; }
        public string Descriere { get; set; }
        public Nullable<float> CostPerHour { get; set; }
        public Nullable<float> RoundingType { get; set; }
        public Nullable<float> MinMinutes { get; set; }
        public Nullable<float> Tolerance { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
