//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEventsOption
    {
        public int EventID { get; set; }
        public int OptionID { get; set; }
        public Nullable<float> Cantitate { get; set; }
        public Nullable<float> PretUnitar { get; set; }
        public Nullable<float> CursValutar { get; set; }
        public Nullable<float> Valoare { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
