//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delegati
    {
        public int AutoID { get; set; }
        public string Nume { get; set; }
        public string BI { get; set; }
        public string Eliberat { get; set; }
        public string MijTransport { get; set; }
        public string NrAuto { get; set; }
    }
}
