//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounturi
    {
        public int DiscountID { get; set; }
        public string Denumire { get; set; }
        public Nullable<int> Tip { get; set; }
        public string Parametrii { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
