//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisponibilPentru
    {
        public Nullable<int> MenuItemID { get; set; }
        public Nullable<bool> Site { get; set; }
        public Nullable<bool> Glovo { get; set; }
        public Nullable<bool> Tazz { get; set; }
        public Nullable<bool> Bolt { get; set; }
        public Nullable<bool> Takeaway { get; set; }
        public Nullable<int> MenuGroupIDGlovo { get; set; }
        public string Poza { get; set; }
        public Nullable<int> MenuGroupIDSite { get; set; }
        public Nullable<bool> Glovo2 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
