//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diverse
    {
        public int DiverseID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> InventoryVendorID { get; set; }
        public string TipAct { get; set; }
        public Nullable<int> NrAct { get; set; }
        public Nullable<float> Baza { get; set; }
        public Nullable<float> TVA { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<bool> Achitata { get; set; }
        public Nullable<float> Platit { get; set; }
        public Nullable<float> Rest { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
