//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeFile()
        {
            this.ComplimentaryAmounts = new HashSet<ComplimentaryAmount>();
            this.CustomerCredits = new HashSet<CustomerCredit>();
            this.Emails = new HashSet<Email>();
            this.Emails1 = new HashSet<Email>();
            this.AccessDeniedLogs = new HashSet<AccessDeniedLog>();
            this.EmployeePayrollHistories = new HashSet<EmployeePayrollHistory>();
            this.EmployeeSchedules = new HashSet<EmployeeSchedule>();
            this.EmployeeTimeCards = new HashSet<EmployeeTimeCard>();
            this.FreqDinerTrackings = new HashSet<FreqDinerTracking>();
            this.GiftCertificates = new HashSet<GiftCertificate>();
            this.GiftCertificateUsages = new HashSet<GiftCertificateUsage>();
            this.NoSaleLogs = new HashSet<NoSaleLog>();
            this.OnAccountCharges = new HashSet<OnAccountCharge>();
            this.OnAccountPayments = new HashSet<OnAccountPayment>();
            this.OrderCheckDriverLicenseLogs = new HashSet<OrderCheckDriverLicenseLog>();
            this.OrderHeaders = new HashSet<OrderHeader>();
            this.OrderHeaders1 = new HashSet<OrderHeader>();
            this.OrderPayments = new HashSet<OrderPayment>();
            this.OrderRefunds = new HashSet<OrderRefund>();
            this.OrderVoidLogs = new HashSet<OrderVoidLog>();
            this.OtherPayments = new HashSet<OtherPayment>();
            this.PayOuts = new HashSet<PayOut>();
            this.PayOuts1 = new HashSet<PayOut>();
            this.PrankCallFiles = new HashSet<PrankCallFile>();
            this.RegisterCashiers = new HashSet<RegisterCashier>();
            this.RegisterCashiers1 = new HashSet<RegisterCashier>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string MailingAddress { get; set; }
        public string MailingZipCode { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public bool EmployeeInActive { get; set; }
        public int JobTitleID { get; set; }
        public string SecurityLevel { get; set; }
        public string AccessCode { get; set; }
        public bool TipsReceived { get; set; }
        public string PayBasis { get; set; }
        public float PayRate { get; set; }
        public string ScanCode { get; set; }
        public string DriverLicenseNumber { get; set; }
        public Nullable<System.DateTime> DriverLicenseExpires { get; set; }
        public string CarInsurancePolicyCarrier { get; set; }
        public string CarInsurancePolicyNumber { get; set; }
        public Nullable<System.DateTime> CarInsurancePolicyExpires { get; set; }
        public string CarInsurancePolicyNotes { get; set; }
        public string PrefUserInterfaceLocale { get; set; }
        public string EmployeeNotes { get; set; }
        public bool OrderEntryUseSecLang { get; set; }
        public bool EmployeeIsDriver { get; set; }
        public Nullable<int> DefaultOEMenuGroupID { get; set; }
        public Nullable<bool> UseStaffBank { get; set; }
        public Nullable<bool> ScheduleNotEnforced { get; set; }
        public Nullable<bool> UseHostess { get; set; }
        public Nullable<bool> IsAServer { get; set; }
        public Nullable<bool> NoCashierOut { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public Nullable<bool> DineInNotAvail { get; set; }
        public Nullable<bool> BarNotAvail { get; set; }
        public Nullable<bool> TakeOutNotAvail { get; set; }
        public Nullable<bool> DriveThruNotAvail { get; set; }
        public Nullable<bool> DeliveryNotAvail { get; set; }
        public Nullable<bool> UseEmail { get; set; }
        public string EmailAddress { get; set; }
        public string PictureName { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public Nullable<short> HolidayPayScale { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplimentaryAmount> ComplimentaryAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCredit> CustomerCredits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessDeniedLog> AccessDeniedLogs { get; set; }
        public virtual ZipCode ZipCode { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual ZipCode ZipCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePayrollHistory> EmployeePayrollHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSchedule> EmployeeSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTimeCard> EmployeeTimeCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreqDinerTracking> FreqDinerTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftCertificate> GiftCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftCertificateUsage> GiftCertificateUsages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoSaleLog> NoSaleLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnAccountCharge> OnAccountCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnAccountPayment> OnAccountPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCheckDriverLicenseLog> OrderCheckDriverLicenseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHeader> OrderHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHeader> OrderHeaders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRefund> OrderRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderVoidLog> OrderVoidLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherPayment> OtherPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayOut> PayOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayOut> PayOuts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrankCallFile> PrankCallFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterCashier> RegisterCashiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterCashier> RegisterCashiers1 { get; set; }
    }
}
