//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayrollHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeePayrollHistory()
        {
            this.EmployeeTimeCards = new HashSet<EmployeeTimeCard>();
        }
    
        public int PayrollID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime PayPeriodBeginDate { get; set; }
        public System.DateTime PayPeriodEndDate { get; set; }
        public string PayBasis { get; set; }
        public float PayRate { get; set; }
        public Nullable<float> OTPayRate { get; set; }
        public Nullable<float> AdditionalPay { get; set; }
        public Nullable<float> RegularHours { get; set; }
        public Nullable<float> OverTimeHours { get; set; }
        public Nullable<float> TotalTips { get; set; }
        public Nullable<float> TotalWageAdvance { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public Nullable<float> DoubleTimeHours { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual EmployeeFile EmployeeFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTimeCard> EmployeeTimeCards { get; set; }
    }
}
