//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpContHistory
    {
        public int AutoID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> ExportID { get; set; }
        public string ActeIncluse { get; set; }
        public string Perioada { get; set; }
        public Nullable<System.DateTime> DataStart { get; set; }
        public Nullable<System.DateTime> DataEnd { get; set; }
        public string ProgCont { get; set; }
        public string Param { get; set; }
    }
}
