//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturiOrder
    {
        public Nullable<int> FacturaID { get; set; }
        public Nullable<int> FacturaMethod { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public Nullable<float> AmountDue { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OrderChargeID { get; set; }
        public Nullable<int> OrderChargePaymentID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
