//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetaliiPlata
    {
        public int AutoID { get; set; }
        public Nullable<int> FacturaID { get; set; }
        public Nullable<int> Platita { get; set; }
        public Nullable<float> SumaPlatita { get; set; }
        public Nullable<float> RamasDePlatit { get; set; }
        public string IDChitanteSume { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Facturi Facturi { get; set; }
    }
}
