//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturiMarfaDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturiMarfaDetail()
        {
            this.FacturiMarfaExplosions = new HashSet<FacturiMarfaExplosion>();
        }
    
        public int AutoID { get; set; }
        public Nullable<int> FacturaID { get; set; }
        public string DetailText { get; set; }
        public string UM { get; set; }
        public Nullable<float> Cantitate { get; set; }
        public Nullable<float> PretUnitar { get; set; }
        public Nullable<float> CotaTVA { get; set; }
        public Nullable<float> ValFaraTVA { get; set; }
        public Nullable<float> TVA { get; set; }
        public Nullable<float> ValCuTVA { get; set; }
        public Nullable<int> InventoryItemID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual FacturiMarfa FacturiMarfa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturiMarfaExplosion> FacturiMarfaExplosions { get; set; }
    }
}
