//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturiDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturiDetail()
        {
            this.FacturiExplosions = new HashSet<FacturiExplosion>();
        }
    
        public int AutoID { get; set; }
        public Nullable<int> FacturaID { get; set; }
        public string DetailText { get; set; }
        public string UM { get; set; }
        public Nullable<float> Cantitate { get; set; }
        public Nullable<float> PretUnitar { get; set; }
        public Nullable<float> CotaTVA { get; set; }
        public Nullable<float> ValFaraTVA { get; set; }
        public Nullable<float> TVA { get; set; }
        public Nullable<float> ValCuTVA { get; set; }
        public Nullable<int> MenuItemID { get; set; }
        public Nullable<float> PretUnitarV { get; set; }
        public Nullable<float> ValFaraTVAV { get; set; }
        public Nullable<float> TVAV { get; set; }
        public Nullable<float> ValCuTVAV { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Facturi Facturi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturiExplosion> FacturiExplosions { get; set; }
    }
}
