//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSetting
    {
        public string RestaurantName { get; set; }
        public Nullable<int> SiteNumber { get; set; }
        public string PremiseAddress { get; set; }
        public string PremiseZipCode { get; set; }
        public string MailingAddress { get; set; }
        public string MailingZipCode { get; set; }
        public Nullable<float> DefaultDeliveryCharge { get; set; }
        public Nullable<float> DefaultDeliveryComp { get; set; }
        public bool DineInService { get; set; }
        public bool TakeOutService { get; set; }
        public bool DriveThruService { get; set; }
        public bool DeliveryService { get; set; }
        public bool QuickService { get; set; }
        public bool AcceptCheck { get; set; }
        public bool AcceptVisa { get; set; }
        public bool AcceptMastercard { get; set; }
        public bool AcceptAmericanExpress { get; set; }
        public bool AcceptNovusCards { get; set; }
        public bool AcceptATM { get; set; }
        public bool AcceptCarteBlanche { get; set; }
        public bool AcceptDinersInternational { get; set; }
        public bool AcceptOnAccount { get; set; }
        public float SalesTaxRate { get; set; }
        public bool ConfirmExitProgram { get; set; }
        public bool AutoPrintOrder { get; set; }
        public bool AutoPrintReceipt { get; set; }
        public Nullable<float> FreqDinerMinTicket { get; set; }
        public Nullable<System.DateTime> FreqDinerStartTime { get; set; }
        public Nullable<System.DateTime> FreqDinerStopTime { get; set; }
        public bool KitchenUseSecLang { get; set; }
        public bool BarUseSecLang { get; set; }
        public string PayPeriod { get; set; }
        public float HourlyOverTimePercent { get; set; }
        public string OnAccountDueDay { get; set; }
        public string GuestReceiptMessage { get; set; }
        public bool TakeOutOnHoldForNewCust { get; set; }
        public string KitchenPrefLocaleID { get; set; }
        public string BarPrefLocaleID { get; set; }
        public Nullable<int> AutoGratuityPercent { get; set; }
        public bool AutoPrintGratuityClaimReceipt { get; set; }
        public string LastDayOfWorkWeek { get; set; }
        public bool PrintCreditCardTipLine { get; set; }
        public string PictureName { get; set; }
        public float OverTimeHoursAfter { get; set; }
        public string OverTimeHourBasis { get; set; }
        public string CallerIDComPort { get; set; }
        public Nullable<float> GSTRate { get; set; }
        public bool PerformCheckScan { get; set; }
        public string GuestCheckPrefLocaleID { get; set; }
        public bool GuestCheckUseSecLang { get; set; }
        public bool OrderEntrySingleItem { get; set; }
        public bool ServerBanking { get; set; }
        public bool HideGreenIndicatorOnSavedOrder { get; set; }
        public bool HideVoidedItemFromPrintedGuestCheck { get; set; }
        public bool RecallOrderByTable { get; set; }
        public bool ForceClearInUseTable { get; set; }
        public bool HideModifierFromGuestCheckWithoutCost { get; set; }
        public bool HideModifierCostFromGuestCheck { get; set; }
        public bool TrackGuestNumber { get; set; }
        public System.DateTime LunchStartTime { get; set; }
        public System.DateTime DinnerStartTime { get; set; }
        public bool PerformMenuExplosion { get; set; }
        public bool IntegratedCreditCardProcessing { get; set; }
        public int MinimumRecipeProfitMarginPercent { get; set; }
        public bool HideOrderHoldUntilTimeFromPrintedGuestCheck { get; set; }
        public bool HideItemHoldUntilTimeFromPrintedGuestCheck { get; set; }
        public bool HideExpiredHoldTime { get; set; }
        public Nullable<int> EDCTimeOut { get; set; }
        public string EDCLastValidYear { get; set; }
        public string EDCActiveChargePath { get; set; }
        public string EDCUserName { get; set; }
        public Nullable<int> EDCReceiptCopies { get; set; }
        public bool HideVoidedMenuItemFromScreen { get; set; }
        public Nullable<int> FreqDinerRewardAfterCount { get; set; }
        public Nullable<float> FreqDinerRewardAfterAmount { get; set; }
        public Nullable<float> FreqDinerRewardCreditAmount { get; set; }
        public bool AutomaticFreqDinerRewardCreation { get; set; }
        public string DailySpecialsMessage { get; set; }
        public bool DisplayDailySpecials { get; set; }
        public bool DesignatedDriveThruStations { get; set; }
        public bool DisableDriveThruTiming { get; set; }
        public int AutoID { get; set; }
        public string ModBuilderType1 { get; set; }
        public string PhoneNumber { get; set; }
        public string DefaultAreaCode { get; set; }
        public string ModBuilderType2 { get; set; }
        public string ModBuilderType3 { get; set; }
        public string ModBuilderType4 { get; set; }
        public string ModBuilderType5 { get; set; }
        public string ModBuilderType6 { get; set; }
        public string ModBuilderType7 { get; set; }
        public string ModBuilderType8 { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public Nullable<System.DateTime> LastPollTimestamp { get; set; }
        public Nullable<System.DateTime> LastSynchVer { get; set; }
        public string ExtendedSettings { get; set; }
        public string HostessSettings { get; set; }
        public string PCCSettings { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual ZipCode ZipCode { get; set; }
        public virtual ZipCode ZipCode1 { get; set; }
    }
}
