//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestiuni
    {
        public int id { get; set; }
        public string nume_gestiune { get; set; }
        public string descriere { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsGlobal { get; set; }
        public Nullable<bool> IPV { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
