//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCertificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiftCertificate()
        {
            this.GiftCertificateUsages = new HashSet<GiftCertificateUsage>();
            this.OtherPayments = new HashSet<OtherPayment>();
        }
    
        public int GiftCertificateID { get; set; }
        public System.DateTime IssuedDateTime { get; set; }
        public string InternalSequenceNumber { get; set; }
        public int EmployeeID { get; set; }
        public string IssuedToName { get; set; }
        public string PresentedByName { get; set; }
        public float IssuedAmount { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string GiftCertificateStatus { get; set; }
        public string GCVoidReason { get; set; }
        public string ScanCode { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string GCSAcctNo { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual EmployeeFile EmployeeFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftCertificateUsage> GiftCertificateUsages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherPayment> OtherPayments { get; set; }
    }
}
