//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryClient
    {
        public int InventoryClientID { get; set; }
        public string InventoryClientText { get; set; }
        public Nullable<bool> InventoryClientInActive { get; set; }
        public string RowGUID { get; set; }
        public string InventoryClientText2 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
