//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryClientsInfo
    {
        public int InventoryClientID { get; set; }
        public string CodFiscal { get; set; }
        public string Localitate { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Banca { get; set; }
        public string Cont { get; set; }
        public string DateContact { get; set; }
        public string AlteInformatii { get; set; }
        public Nullable<float> Sold { get; set; }
        public string NrInreg { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string NrJ { get; set; }
        public string Adresa2 { get; set; }
        public Nullable<bool> TVAI { get; set; }
        public Nullable<float> TermenDePlata { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
