//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemsInfo
    {
        public int InventoryItemID { get; set; }
        public Nullable<float> UltimulPretAchizitie { get; set; }
        public Nullable<float> UltimulPretVanzare { get; set; }
        public Nullable<float> UltimaValoareAchizitie { get; set; }
        public Nullable<float> UltimaValoareVanzare { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
