//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryItem()
        {
            this.InventoryPhysicalCounts = new HashSet<InventoryPhysicalCount>();
            this.MenuExplosions = new HashSet<MenuExplosion>();
            this.MenuItemIngredients = new HashSet<MenuItemIngredient>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        public int InventoryItemID { get; set; }
        public string InventoryItemText { get; set; }
        public string InventoryItemUnitName { get; set; }
        public string InventoryItemDescription { get; set; }
        public int InventoryItemGroupID { get; set; }
        public int InventoryItemLocationID { get; set; }
        public int ItemDisplaySeqNumber { get; set; }
        public bool InventoryItemInActive { get; set; }
        public float InventoryItemReOrderPoint { get; set; }
        public float CurrentQtyOnHand { get; set; }
        public float CurrentValueOnHand { get; set; }
        public float CurrentUnitCost { get; set; }
        public Nullable<System.DateTime> LastUpdateDateTime { get; set; }
        public string InventoryItemSecLang { get; set; }
        public int InventoryVendorID { get; set; }
        public float ReOrderLevel { get; set; }
        public float MenuIngredientUnitsPerBaseQty { get; set; }
        public string PackSizeBarcode { get; set; }
        public string EachItemBarcode { get; set; }
        public Nullable<int> TotalItemsPerPackSize { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual InventoryGroup InventoryGroup { get; set; }
        public virtual InventoryVendor InventoryVendor { get; set; }
        public virtual InventoryLocation InventoryLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryPhysicalCount> InventoryPhysicalCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuExplosion> MenuExplosions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItemIngredient> MenuItemIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    }
}
