//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemsGroupsGlovo
    {
        public Nullable<int> MenuGroupID { get; set; }
        public string MenuGroupText { get; set; }
        public Nullable<bool> Front { get; set; }
        public Nullable<bool> Ascuns { get; set; }
        public string Descriere { get; set; }
        public string Minim { get; set; }
        public string Maxim { get; set; }
        public Nullable<int> Ordine { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
