//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuModifier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuModifier()
        {
            this.MenuModifierPopUps = new HashSet<MenuModifierPopUp>();
        }
    
        public int MenuModifierID { get; set; }
        public string MenuModifierText { get; set; }
        public Nullable<float> AdditionalCost { get; set; }
        public bool MenuModifierInActive { get; set; }
        public string SecLangModifierText { get; set; }
        public string PictureName { get; set; }
        public bool ShowCaption { get; set; }
        public bool PizzaCrust { get; set; }
        public bool PizzaTopping { get; set; }
        public bool BarMixer { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public Nullable<short> PizzaSize { get; set; }
        public string ScreenName { get; set; }
        public string ScreenAltName { get; set; }
        public string ReceiptName { get; set; }
        public string ReceiptAltName { get; set; }
        public string ChitName { get; set; }
        public string ChitAltName { get; set; }
        public Nullable<bool> PizzaSauce { get; set; }
        public Nullable<int> LCPLU { get; set; }
        public Nullable<short> ActionType { get; set; }
        public Nullable<int> ActionBaseModifierID { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuModifierPopUp> MenuModifierPopUps { get; set; }
    }
}
