//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModBuilderDetail
    {
        public int ModBuilderDetailID { get; set; }
        public int ModBuilderTemplateID { get; set; }
        public short ModBuilderType { get; set; }
        public int MenuModifierID { get; set; }
        public Nullable<float> AdditionalCost { get; set; }
        public Nullable<int> NoTypeModifierID { get; set; }
        public Nullable<float> NoTypeCost { get; set; }
        public Nullable<int> AddTypeModifierID { get; set; }
        public Nullable<float> AddTypeCost { get; set; }
        public Nullable<int> ExtraTypeModifierID { get; set; }
        public Nullable<float> ExtraTypeCost { get; set; }
        public Nullable<int> LightTypeModifierID { get; set; }
        public Nullable<float> LightTypeCost { get; set; }
        public Nullable<int> ExchgTypeModifierID { get; set; }
        public Nullable<float> ExchgTypeCost { get; set; }
        public Nullable<int> DoubleTypeModifierID { get; set; }
        public Nullable<float> DoubleTypeCost { get; set; }
        public Nullable<int> TripleTypeModifierID { get; set; }
        public Nullable<float> TripleTypeCost { get; set; }
        public Nullable<int> HalfTypeModifierID { get; set; }
        public Nullable<float> HalfTypeCost { get; set; }
        public short DisplayIndex { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public Nullable<bool> ExcludeBaseModifier { get; set; }
        public Nullable<bool> SelectedAsDefault { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
