//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModBuilderTemplate
    {
        public int ModBuilderTemplateID { get; set; }
        public string ModBuilderTemplateText { get; set; }
        public bool UseModBuilderType1 { get; set; }
        public bool UseModBuilderType2 { get; set; }
        public bool UseModBuilderType3 { get; set; }
        public bool UseModBuilderType4 { get; set; }
        public bool UseModBuilderType5 { get; set; }
        public bool UseModBuilderType6 { get; set; }
        public bool UseModBuilderType7 { get; set; }
        public bool UseModBuilderType8 { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string Type1Name { get; set; }
        public string Type2Name { get; set; }
        public string Type3Name { get; set; }
        public string Type4Name { get; set; }
        public string Type5Name { get; set; }
        public string Type6Name { get; set; }
        public string Type7Name { get; set; }
        public string Type8Name { get; set; }
        public Nullable<short> Type1DefaultAction { get; set; }
        public Nullable<short> Type2DefaultAction { get; set; }
        public Nullable<short> Type3DefaultAction { get; set; }
        public Nullable<short> Type4DefaultAction { get; set; }
        public Nullable<short> Type5DefaultAction { get; set; }
        public Nullable<short> Type6DefaultAction { get; set; }
        public Nullable<short> Type7DefaultAction { get; set; }
        public Nullable<short> Type8DefaultAction { get; set; }
        public Nullable<short> Type1MinSelect { get; set; }
        public Nullable<short> Type1MaxSelect { get; set; }
        public Nullable<short> Type2MinSelect { get; set; }
        public Nullable<short> Type2MaxSelect { get; set; }
        public Nullable<short> Type3MinSelect { get; set; }
        public Nullable<short> Type3MaxSelect { get; set; }
        public Nullable<short> Type4MinSelect { get; set; }
        public Nullable<short> Type4MaxSelect { get; set; }
        public Nullable<short> Type5MinSelect { get; set; }
        public Nullable<short> Type5MaxSelect { get; set; }
        public Nullable<short> Type6MinSelect { get; set; }
        public Nullable<short> Type6MaxSelect { get; set; }
        public Nullable<short> Type7MinSelect { get; set; }
        public Nullable<short> Type7MaxSelect { get; set; }
        public Nullable<short> Type8MinSelect { get; set; }
        public Nullable<short> Type8MaxSelect { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
