//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiruriDetail
    {
        public Nullable<int> NirID { get; set; }
        public string Produs { get; set; }
        public Nullable<int> InventoryItemID { get; set; }
        public Nullable<float> Cantitate { get; set; }
        public string UnitName { get; set; }
        public Nullable<float> PUC { get; set; }
        public Nullable<float> TVAUC { get; set; }
        public Nullable<float> VUC { get; set; }
        public Nullable<float> VFTVAC { get; set; }
        public Nullable<float> TVAC { get; set; }
        public Nullable<float> VTC { get; set; }
        public Nullable<float> PUV { get; set; }
        public Nullable<float> TVAUV { get; set; }
        public Nullable<float> VUV { get; set; }
        public Nullable<float> VFTVAV { get; set; }
        public Nullable<float> TVAV { get; set; }
        public Nullable<float> VTV { get; set; }
        public Nullable<float> AdaosT { get; set; }
        public Nullable<float> AdaosU { get; set; }
        public Nullable<float> AdaosP { get; set; }
        public int NirDetailsID { get; set; }
        public Nullable<int> NirOrder { get; set; }
        public Nullable<bool> HasDiscount { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<float> DiscountProcent { get; set; }
        public Nullable<float> DiscountSuma { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public Nullable<bool> IsGlobal { get; set; }
        public Nullable<float> PUI { get; set; }
        public Nullable<float> VUI { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
