//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Niruri
    {
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> InventoryVendorID { get; set; }
        public Nullable<int> nrNir { get; set; }
        public string nrFactura { get; set; }
        public Nullable<float> TotalC { get; set; }
        public Nullable<float> TotalV { get; set; }
        public Nullable<float> Adaos { get; set; }
        public Nullable<int> GestiuneID { get; set; }
        public string TipAct { get; set; }
        public int NirID { get; set; }
        public Nullable<bool> Achitata { get; set; }
        public Nullable<float> Platit { get; set; }
        public Nullable<float> Rest { get; set; }
        public Nullable<int> NStatus { get; set; }
        public string SerieNIR { get; set; }
        public string SerieFactura { get; set; }
        public string CodValuta { get; set; }
        public Nullable<double> CursValuta { get; set; }
        public string nrNirAditional { get; set; }
        public string DlgNume { get; set; }
        public string DlgBI { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
