//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayOut
    {
        public int PayOutID { get; set; }
        public System.DateTime PayOutDateTime { get; set; }
        public int CashierID { get; set; }
        public Nullable<int> NonCashierEmployeeID { get; set; }
        public string PayOutToName { get; set; }
        public string PayOutDescription { get; set; }
        public float PayOutAmount { get; set; }
        public Nullable<int> WageAdvanceEmployeeID { get; set; }
        public bool PayOutVoided { get; set; }
        public string VoidReason { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual EmployeeFile EmployeeFile { get; set; }
        public virtual EmployeeFile EmployeeFile1 { get; set; }
        public virtual RegisterCashier RegisterCashier { get; set; }
    }
}
