//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoaneSolduri
    {
        public Nullable<int> PersoanaID { get; set; }
        public string Cod { get; set; }
        public Nullable<float> Sold { get; set; }
        public string Garantii { get; set; }
        public Nullable<float> Intrare { get; set; }
        public string Comenzi { get; set; }
        public string Intrari { get; set; }
        public string ModalitatePlata { get; set; }
        public string UltimaDataAlimentare { get; set; }
        public string DiscountID { get; set; }
        public string DiscountAmount { get; set; }
        public string DiscountBasis { get; set; }
        public Nullable<bool> Activata { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
