//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdOrderTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdOrderTransaction()
        {
            this.ProdOrderExplosions = new HashSet<ProdOrderExplosion>();
        }
    
        public int OrderTransactionID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> InventoryItemID { get; set; }
        public Nullable<float> Quantity { get; set; }
        public Nullable<float> UnitCost { get; set; }
        public Nullable<float> TotalValue { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdOrderExplosion> ProdOrderExplosions { get; set; }
        public virtual ProdOrderHeader ProdOrderHeader { get; set; }
    }
}
