//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdOrderHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdOrderHeader()
        {
            this.ProdOrderTransactions = new HashSet<ProdOrderTransaction>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> Numar { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Descriere { get; set; }
        public Nullable<float> Valoare { get; set; }
        public Nullable<int> GestiuneID { get; set; }
        public Nullable<int> CSSessionID { get; set; }
        public Nullable<int> NirID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdOrderTransaction> ProdOrderTransactions { get; set; }
    }
}
