//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuncteLucru
    {
        public int PunctLucruID { get; set; }
        public string Cod { get; set; }
        public string Name { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> FurnizorID { get; set; }
        public string Other { get; set; }
    }
}
