//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVHistory
    {
        public Nullable<System.DateTime> Data { get; set; }
        public int ChangeID { get; set; }
        public int InventoryItemID { get; set; }
        public Nullable<float> Stock { get; set; }
        public Nullable<float> OldPrice { get; set; }
        public Nullable<float> NewPrice { get; set; }
        public Nullable<float> DiffValue { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
