//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapFisaMagazie
    {
        public Nullable<System.DateTime> DateForOrder { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Informatie { get; set; }
        public Nullable<float> Intrat { get; set; }
        public Nullable<float> Iesit { get; set; }
        public Nullable<float> Stoc { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
