//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapFidelizare
    {
        public Nullable<int> PersoanaID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<float> Valoare { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
