//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapOspatariDetaliat
    {
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> GestiuneID { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<float> Discount { get; set; }
        public Nullable<float> Cash { get; set; }
        public Nullable<float> ATM { get; set; }
        public Nullable<float> Other { get; set; }
        public Nullable<float> CEC { get; set; }
        public Nullable<float> Ticket { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
