//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapProfitVanzare
    {
        public Nullable<int> MenuItemID { get; set; }
        public Nullable<float> UnitatiVandute { get; set; }
        public Nullable<float> CostTotal { get; set; }
        public Nullable<float> VanzareTotala { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
