//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapVanzariAchizitii
    {
        public Nullable<int> Luna { get; set; }
        public Nullable<int> An { get; set; }
        public Nullable<int> Gestiune { get; set; }
        public Nullable<float> Achizitie { get; set; }
        public Nullable<float> Vanzare { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
