//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapVanzariAnulari
    {
        public string Angajat { get; set; }
        public Nullable<int> Gestiune { get; set; }
        public Nullable<float> Vanzare { get; set; }
        public Nullable<float> Anulare { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
