//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplicationHistory
    {
        public int HistoryID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Type { get; set; }
        public string Documents { get; set; }
        public Nullable<System.DateTime> DataStart { get; set; }
        public Nullable<System.DateTime> DataEnd { get; set; }
        public string FileName { get; set; }
    }
}
