//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplicationMapNoText
    {
        public int DataBaseID { get; set; }
        public int Tip { get; set; }
        public int RemoteID { get; set; }
        public Nullable<int> LocalID { get; set; }
    }
}
