//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezervariHotel
    {
        public int AutoID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> DataSosire { get; set; }
        public Nullable<System.DateTime> DataPlecare { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> TipRezervareID { get; set; }
        public Nullable<int> NumarAdulti { get; set; }
        public Nullable<int> NumarCopii { get; set; }
        public Nullable<float> Avans { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
