//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int AutoID { get; set; }
        public Nullable<int> NumarCamera { get; set; }
        public Nullable<int> Etaj { get; set; }
        public Nullable<int> RoomsCaracteristics1ID { get; set; }
        public Nullable<int> RoomsCaracteristics2ID { get; set; }
        public Nullable<int> RoomsCaracteristics3ID { get; set; }
        public Nullable<int> SingleBed { get; set; }
        public Nullable<int> DoubleBed { get; set; }
        public Nullable<int> ExtraBed { get; set; }
        public string AlteOptiuni { get; set; }
    }
}
