//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsCaracteristics3
    {
        public int AutoID { get; set; }
        public string NumeCaracteristica { get; set; }
        public string Descriere { get; set; }
    }
}
