//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RowChanx
    {
        public int AutoID { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string DBTableName { get; set; }
        public string SourceRowGUID { get; set; }
        public bool SourceRowDeleteAction { get; set; }
        public string DirectSQL { get; set; }
        public bool Mirrored { get; set; }
        public bool HQSynched { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
