//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocuriSession
    {
        public Nullable<System.DateTime> Data { get; set; }
        public string Descriere { get; set; }
        public int SessionID { get; set; }
        public Nullable<float> OldValue { get; set; }
        public Nullable<float> NewValue { get; set; }
        public Nullable<float> UsedValue { get; set; }
        public Nullable<bool> Alb { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
