//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubreteteDetail
    {
        public int SubretetaDetailsID { get; set; }
        public Nullable<int> SubretetaID { get; set; }
        public Nullable<int> InventoryItemID { get; set; }
        public Nullable<float> UnitsUsed { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
