//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taxe()
        {
            this.TaxeDetaliis = new HashSet<TaxeDetalii>();
        }
    
        public int IDTaxa { get; set; }
        public Nullable<int> Procent { get; set; }
        public Nullable<int> IDElementMeniuAsociat { get; set; }
        public Nullable<int> VIDElementMeniuAsociat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxeDetalii> TaxeDetaliis { get; set; }
    }
}
