//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpAux
    {
        public int AutoID { get; set; }
        public Nullable<int> MenuItemID { get; set; }
        public string MenuItemText { get; set; }
        public Nullable<float> Suma { get; set; }
        public Nullable<int> Cantitate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
