//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpMenuExplosion
    {
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> OrderTransactionID { get; set; }
        public Nullable<int> InventoryItemID { get; set; }
        public Nullable<float> TotalUnitsUsed { get; set; }
        public int AutoID { get; set; }
        public Nullable<float> MenuIngredientUnitCost { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
