//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpRapConsumTotal
    {
        public Nullable<int> InventoryItemID { get; set; }
        public Nullable<float> Cantitate { get; set; }
        public Nullable<float> VFTVAC { get; set; }
        public Nullable<float> TVAC { get; set; }
        public Nullable<float> TVAV { get; set; }
        public Nullable<float> VTV { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string NrBonConsum { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
