//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpRapOspatariGlobal
    {
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<float> DiscountGlobal { get; set; }
        public Nullable<float> GratuitatiGlobal { get; set; }
        public Nullable<float> SuprataxaGlobal { get; set; }
        public Nullable<float> DeliveryTaxGlobal { get; set; }
        public Nullable<float> CreditGlobal { get; set; }
        public Nullable<float> Cash { get; set; }
        public Nullable<float> ATM { get; set; }
        public Nullable<float> Other { get; set; }
        public Nullable<float> Neincasat { get; set; }
        public Nullable<float> CEC { get; set; }
        public Nullable<float> Ticket { get; set; }
        public Nullable<int> OrdersCount { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
