//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpRapEvolutieGestiune
    {
        public Nullable<int> InventoryItemID { get; set; }
        public Nullable<float> StocInitial { get; set; }
        public Nullable<float> Intrari { get; set; }
        public Nullable<float> Consum { get; set; }
        public Nullable<float> Iesiri { get; set; }
        public Nullable<float> Ajustari { get; set; }
        public Nullable<float> StocFinal { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
