//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferuri
    {
        public int ID { get; set; }
        public Nullable<int> ProdusSursa { get; set; }
        public Nullable<int> ProdusDestinatie { get; set; }
        public Nullable<int> GestiuneSursa { get; set; }
        public Nullable<int> GestiuneDestinatie { get; set; }
        public Nullable<float> Cantitate { get; set; }
        public string UM { get; set; }
        public string Comment { get; set; }
        public string Utilizator { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<bool> IsRemote { get; set; }
        public Nullable<int> DBID { get; set; }
        public Nullable<bool> IsGestiune1Global { get; set; }
        public Nullable<bool> IsGestiune2Global { get; set; }
        public Nullable<float> Valoare { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
