//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInventoryItem
    {
        public int InventoryItemID { get; set; }
        public string InventoryItemText { get; set; }
        public string InventoryItemUnitName { get; set; }
        public string InventoryItemDescription { get; set; }
        public Nullable<int> InventoryItemGroupID { get; set; }
        public Nullable<int> InventoryItemLocationID { get; set; }
        public Nullable<int> ItemDisplaySeqNumber { get; set; }
        public Nullable<bool> InventoryItemInActive { get; set; }
        public Nullable<float> InventoryItemReOrderPoint { get; set; }
        public Nullable<float> CurrentQtyOnHand { get; set; }
        public Nullable<float> CurrentValueOnHand { get; set; }
        public Nullable<float> CurrentUnitCost { get; set; }
        public Nullable<System.DateTime> LastUpdateDateTime { get; set; }
        public string InventoryItemSecLang { get; set; }
        public Nullable<int> InventoryVendorID { get; set; }
        public Nullable<float> ReOrderLevel { get; set; }
        public Nullable<float> MenuIngredientUnitsPerBaseQty { get; set; }
        public string PackSizeBarcode { get; set; }
        public string EachItemBarcode { get; set; }
        public Nullable<int> TotalItemsPerPackSize { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<short> RemoteSiteNumber { get; set; }
        public Nullable<int> RemoteOrigRowID { get; set; }
        public string GlobalID { get; set; }
        public string RowVer { get; set; }
        public Nullable<System.DateTime> SynchVer { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string HQRowID { get; set; }
        public string LastRowHash { get; set; }
        public Nullable<short> RowOwner { get; set; }
        public string RowGUID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
